import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: 'products',
      columns: [
        { name: 'server_id', type: 'string' },
        { name: 'name', type: 'string' },
        { name: 'sku', type: 'string' },
        { name: 'barcode', type: 'string', isOptional: true },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'category_id', type: 'string', isOptional: true },
        { name: 'unit_price', type: 'number' },
        { name: 'cost_price', type: 'number', isOptional: true },
        { name: 'stock_quantity', type: 'number' },
        { name: 'min_stock_level', type: 'number' },
        { name: 'expiration_date', type: 'number', isOptional: true },
        { name: 'image_url', type: 'string', isOptional: true },
        { name: 'version', type: 'number' },
        { name: 'synced', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'customers',
      columns: [
        { name: 'server_id', type: 'string' },
        { name: 'name', type: 'string' },
        { name: 'rif', type: 'string' },
        { name: 'email', type: 'string', isOptional: true },
        { name: 'phone', type: 'string', isOptional: true },
        { name: 'address', type: 'string', isOptional: true },
        { name: 'credit_limit', type: 'number' },
        { name: 'version', type: 'number' },
        { name: 'synced', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'sales',
      columns: [
        { name: 'server_id', type: 'string' },
        { name: 'customer_id', type: 'string', isOptional: true },
        { name: 'vendor_id', type: 'string' },
        { name: 'subtotal', type: 'number' },
        { name: 'iva', type: 'number' },
        { name: 'total', type: 'number' },
        { name: 'currency', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'version', type: 'number' },
        { name: 'synced', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'sale_items',
      columns: [
        { name: 'sale_id', type: 'string', isIndexed: true },
        { name: 'product_id', type: 'string' },
        { name: 'quantity', type: 'number' },
        { name: 'unit_price', type: 'number' },
        { name: 'total', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'credits',
      columns: [
        { name: 'server_id', type: 'string' },
        { name: 'customer_id', type: 'string' },
        { name: 'sale_id', type: 'string', isOptional: true },
        { name: 'amount', type: 'number' },
        { name: 'balance', type: 'number' },
        { name: 'currency', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'payment_due_date', type: 'number' },
        { name: 'version', type: 'number' },
        { name: 'synced', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'sync_queue',
      columns: [
        { name: 'entity_type', type: 'string' },
        { name: 'entity_id', type: 'string' },
        { name: 'operation', type: 'string' },
        { name: 'data', type: 'string' },
        { name: 'created_at', type: 'number' },
      ],
    }),
  ],
});
