global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Node Exporter - Métricas del sistema (CPU, RAM, Disco, Red)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: /metrics

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Monitor de Servicios Externos (Render)
  - job_name: 'render_pings'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://confimax-api-gateway.onrender.com/health
        - https://confimax-auth-service.onrender.com/health
        - https://confimax-inventory-service.onrender.com/health
        - https://confimax-sales-service.onrender.com/health
        - https://confimax-customers-service.onrender.com/health
        - https://confimax-notifications-service.onrender.com/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
