FROM rediscommander/redis-commander:latest

# Configuración de conexión a Upstash Redis
ENV REDIS_HOST=good-iguana-119328.upstash.io
ENV REDIS_PORT=6379
ENV REDIS_PASSWORD=gQAAAAAAAdIgAAIgcDFhNDRkNmE3OTg5YjA0MDBlODE4MzQxMGY5NGVjNmU0Mg
ENV REDIS_TLS=true

# Seguridad de la interfaz web
ENV HTTP_USER=admin
ENV HTTP_PASSWORD=Jackson1
