import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Design System Colors
        surface: '#141313',
        'surface-dim': '#0A0A0A',
        'surface-bright': '#141414',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353434',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#c4c7c8',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        outline: '#8e9192',
        'outline-variant': '#444748',
        'surface-tint': '#c6c6c7',
        primary: '#ffffff',
        'on-primary': '#2f3131',
        'primary-container': '#e2e2e2',
        'on-primary-container': '#636565',
        'inverse-primary': '#5d5f5f',
        secondary: '#c6c6c6',
        'on-secondary': '#303030',
        'secondary-container': '#474747',
        'on-secondary-container': '#b5b5b5',
        tertiary: '#ffffff',
        'on-tertiary': '#2f3131',
        'tertiary-container': '#e2e2e2',
        'on-tertiary-container': '#636565',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#e2e2e2',
        'primary-fixed-dim': '#c6c6c7',
        'on-primary-fixed': '#1a1c1c',
        'on-primary-fixed-variant': '#454747',
        'secondary-fixed': '#e2e2e2',
        'secondary-fixed-dim': '#c6c6c6',
        'on-secondary-fixed': '#1b1b1b',
        'on-secondary-fixed-variant': '#474747',
        'tertiary-fixed': '#e2e2e2',
        'tertiary-fixed-dim': '#c6c6c7',
        'on-tertiary-fixed': '#1a1c1c',
        'on-tertiary-fixed-variant': '#454747',
        background: '#141313',
        'on-background': '#e5e2e1',
        'surface-variant': '#353434',
        'accent-pink': '#CC0597',
        'border-muted': '#262626',
        'data-blue': '#0066FF',
        // Light mode variants
        'light-surface': '#ffffff',
        'light-surface-dim': '#f5f5f5',
        'light-background': '#ffffff',
        'light-on-background': '#1a1a1a',
        'light-on-surface': '#1a1a1a',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
        'sharp': '0px',
      },
      spacing: {
        'unit': '4px',
        'gutter': '1px',
        'margin-page': '40px',
        'margin-mobile': '20px',
      },
      fontFamily: {
        'headline-lg': ['Montserrat', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Montserrat', 'sans-serif'],
        'data-label': ['JetBrains Mono', 'monospace'],
        'display-xl': ['Montserrat', 'sans-serif'],
        'data-value': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'headline-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '800' }],
        'data-label': ['12px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '500' }],
        'display-xl': ['84px', { lineHeight: '1.0', letterSpacing: '-0.04em', fontWeight: '900' }],
        'data-value': ['14px', { lineHeight: '1.2', fontWeight: '700' }],
      },
      animation: {
        'fade-in-up': 'fade-in-up 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'slide-down': 'slide-down 0.3s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'fade-in': 'fade-in 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'slide-up': 'slide-up 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'ping': 'ping 1s cubic-bezier(0, 0, 0.2, 1) infinite',
        'pulse': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-down': {
          '0%': { opacity: '0', transform: 'translateY(-10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'slide-up': {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
};

export default config;